/*
 * Base de conocimiento de pesca deportiva en Argentina.
 *
 * meses: meses de mejor rendimiento (1 = enero ... 12 = diciembre).
 * posibles: meses en que se captura pero con menor rendimiento.
 * Los datos son orientativos: las vedas, cupos y licencias dependen de cada
 * provincia y cambian año a año. Verificar siempre la normativa vigente.
 */
const ESPECIES = {
  // ---------------- AGUA DULCE: LITORAL / CUENCA DEL PLATA ----------------
  dorado: {
    nombre: "Dorado",
    cientifico: "Salminus brasiliensis",
    ambiente: "dulce",
    meses: [9, 10, 11, 2, 3, 4],
    posibles: [1, 5, 8, 12],
    tempAgua: [18, 28],
    horario: "Amanecer y atardecer; correderas, bocas de riachos y cambios de corriente.",
    carnadas: ["Morena viva", "Anguila", "Bagre chico vivo", "Mojarra grande", "Cabeza de sábalo"],
    senuelos: ["Rapala/crankbait de media agua", "Cucharas ondulantes y rotativas grandes", "Moscas streamer (fly)", "Poppers y paseantes de superficie"],
    metodos: ["Spinning / baitcasting desde embarcación", "Trolling (curricán) en canales", "Carnada viva con línea de flote o a la deriva", "Pesca con mosca"],
    equipo: "Caña 1,80–2,10 m de acción media-pesada, multifilamento 30–50 lb, líder de acero o fluorocarbono grueso (dientes filosos).",
    notas: "Especie emblemática; en muchas provincias es obligatoria la devolución o hay cupo de 1 pieza con talla mínima. En Corrientes y otras provincias rige veda reproductiva (aprox. nov–dic)."
  },
  surubi: {
    nombre: "Surubí (pintado / atigrado)",
    cientifico: "Pseudoplatystoma spp.",
    ambiente: "dulce",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 9],
    tempAgua: [20, 30],
    horario: "Principalmente de noche y con agua en crecida; pozones profundos y veriles.",
    carnadas: ["Morena", "Anguila", "Cascarudo", "Bagre", "Cabeza/filet de sábalo"],
    senuelos: ["Jigs pesados de fondo (poco habitual)"],
    metodos: ["Fondo con plomada corrida desde embarcación anclada", "Garreteo (deriva lenta con carnada al fondo)", "Espinel (sólo donde esté permitido)"],
    equipo: "Caña pesada 2,10–2,40 m, reel rotativo, multifilamento 50–80 lb, anzuelo 8/0–10/0 y brazolada de acero.",
    notas: "Talla mínima y cupo según provincia. Se recomienda devolver ejemplares grandes (reproductores)."
  },
  pacu: {
    nombre: "Pacú",
    cientifico: "Piaractus mesopotamicus",
    ambiente: "dulce",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [22, 30],
    horario: "Días calurosos; zonas de vegetación costera y árboles con frutos sobre el agua.",
    carnadas: ["Frutos silvestres (ingá, higo, guayabo)", "Masa de harina y queso", "Mandioca", "Cangrejo", "Maíz"],
    senuelos: ["Moscas imitación fruto (fly)"],
    metodos: ["Fondo liviano con cebado", "Línea de flote bajo la vegetación", "Pesca con mosca"],
    equipo: "Caña media 2,10 m, nylon 0,40–0,50 mm, anzuelo corto y fuerte 2/0–4/0 (mandíbula muy potente).",
    notas: "Muy desconfiado; conviene cebar la zona. Más frecuente en el Paraná superior, Paraguay e Iberá."
  },
  boga: {
    nombre: "Boga",
    cientifico: "Megaleporinus obtusidens",
    ambiente: "dulce",
    meses: [10, 11, 12, 1, 2, 3, 4],
    posibles: [5, 6, 7, 8, 9],
    tempAgua: [16, 28],
    horario: "Todo el día; mejor mañana y tarde. Veriles con corriente moderada.",
    carnadas: ["Masa (harina, polenta, queso rallado, esencias)", "Maíz cocido", "Pan", "Lombriz", "Cebo de soja"],
    senuelos: [],
    metodos: ["Fondo con línea de 1–2 anzuelos y cebado intenso", "Plomada corrida con anzuelo chico", "Línea de flote en remansos"],
    equipo: "Caña 2,40–3,00 m acción media, nylon 0,30–0,40 mm, anzuelos 1/0–3/0.",
    notas: "Una de las especies más buscadas del Litoral y el Delta. Talla mínima en varias provincias (aprox. 42 cm en Entre Ríos)."
  },
  pejerrey: {
    nombre: "Pejerrey bonaerense",
    cientifico: "Odontesthes bonariensis",
    ambiente: "dulce",
    meses: [4, 5, 6, 7, 8, 9],
    posibles: [3, 10, 11],
    tempAgua: [8, 20],
    horario: "Días nublados y con viento leve; mañanas frescas. Pica a media agua.",
    carnadas: ["Mojarra viva o en filet", "Filet de dientudo", "Filet de sábalo o lisa", "Cornalito", "Lombriz (lagunas con agua turbia)"],
    senuelos: ["Cucharitas chicas", "Moscas (fly) tipo streamer pequeño"],
    metodos: ["Línea de flote con 3–4 boyitas (pesca de costa)", "Embarcado a la deriva con líneas de boyas", "Spinning liviano / fly"],
    equipo: "Caña 3,60–4,20 m muy liviana, nylon 0,20–0,25 mm, anzuelos 1–3.",
    notas: "Clásico de lagunas pampeanas y embalses. Cupo diario y talla mínima (aprox. 25 cm) según provincia; en PBA suele haber veda parcial en primavera."
  },
  tararira: {
    nombre: "Tararira",
    cientifico: "Hoplias malabaricus",
    ambiente: "dulce",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 9],
    tempAgua: [18, 30],
    horario: "Días calurosos, entre juncales y camalotes; muy activa al atardecer.",
    carnadas: ["Mojarra viva", "Filet de dientudo", "Rana (donde esté permitido)"],
    senuelos: ["Ranas y ratones de goma antienganche", "Poppers y paseantes", "Spinnerbaits", "Moscas de pelo de ciervo"],
    metodos: ["Spinning / baitcasting con señuelos de superficie", "Pesca con mosca", "Carnada viva con boya"],
    equipo: "Caña 1,80 m acción media-pesada, multifilamento 30 lb, líder de fluorocarbono 40–60 lb o acero fino.",
    notas: "Pesca muy deportiva con señuelos de superficie. Se recomienda captura y devolución."
  },
  bagre: {
    nombre: "Bagre (amarillo / sapo / moncholo)",
    cientifico: "Pimelodus spp. / Rhamdia quelen",
    ambiente: "dulce",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 5, 6, 7, 8, 9],
    tempAgua: [12, 30],
    horario: "Nocturno y con agua turbia; después de lluvias.",
    carnadas: ["Lombriz", "Tripa o hígado de pollo", "Mojarra", "Filet de sábalo", "Masa con sangre"],
    senuelos: [],
    metodos: ["Fondo con plomada fija o corrida", "Línea de mano desde costa"],
    equipo: "Caña 2,40 m acción media, nylon 0,35 mm, anzuelos 1/0–2/0.",
    notas: "Especie de fácil captura para iniciarse. Cuidado con las espinas (aguijones) de las aletas."
  },
  armado: {
    nombre: "Armado (chancho / común)",
    cientifico: "Pterodoras granulosus",
    ambiente: "dulce",
    meses: [5, 6, 7, 8, 9],
    posibles: [3, 4, 10],
    tempAgua: [10, 24],
    horario: "Tarde y noche; pozones y fondos barrosos.",
    carnadas: ["Lombriz", "Tripa de pollo", "Almeja de río", "Masa"],
    senuelos: [],
    metodos: ["Fondo con plomada pesada y dos anzuelos", "Pesca desde barranca o embarcado"],
    equipo: "Caña 2,40–2,70 m acción media-pesada, nylon 0,40–0,50 mm, anzuelos 2/0–4/0.",
    notas: "Muy buscado en invierno en el Paraná inferior y el Delta."
  },
  pati: {
    nombre: "Patí",
    cientifico: "Luciopimelodus pati",
    ambiente: "dulce",
    meses: [9, 10, 11, 12, 1, 2, 3],
    posibles: [4, 5],
    tempAgua: [16, 28],
    horario: "Noche; canales principales con corriente.",
    carnadas: ["Filet de sábalo", "Mojarra", "Morena chica", "Anguila"],
    senuelos: [],
    metodos: ["Fondo embarcado con plomada corrida", "Deriva en canal"],
    equipo: "Caña media-pesada 2,10 m, nylon 0,45 mm, anzuelos 4/0–6/0.",
    notas: "Frecuente en el Paraná medio e inferior."
  },
  palometa: {
    nombre: "Palometa (piraña)",
    cientifico: "Pygocentrus nattereri / Serrasalmus spp.",
    ambiente: "dulce",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [22, 32],
    horario: "Días de calor; remansos y lagunas vinculadas al río.",
    carnadas: ["Carne vacuna", "Filet de pescado", "Mojarra"],
    senuelos: ["Cucharitas chicas"],
    metodos: ["Fondo o flote con brazolada de acero"],
    equipo: "Caña liviana-media, brazolada de acero obligatoria, anzuelos 1/0.",
    notas: "Dientes muy filosos: manipular con pinza."
  },
  carpa: {
    nombre: "Carpa",
    cientifico: "Cyprinus carpio",
    ambiente: "dulce",
    meses: [10, 11, 12, 1, 2, 3, 4],
    posibles: [5, 9],
    tempAgua: [15, 28],
    horario: "Mañana temprano y atardecer; zonas bajas con vegetación.",
    carnadas: ["Maíz cocido", "Masa (harina, polenta, miel)", "Boilies", "Lombriz", "Pan"],
    senuelos: [],
    metodos: ["Fondo con cebado (método carpfishing con 'pelo')", "Método 'feeder'", "Línea de flote"],
    equipo: "Caña 3,00–3,60 m acción media, nylon 0,30–0,35 mm, anzuelos 2–6.",
    notas: "Especie exótica invasora; en general no tiene cupo. Se practica mucho captura y devolución deportiva."
  },
  trucha: {
    nombre: "Trucha (arco iris, marrón, fontinalis)",
    cientifico: "Oncorhynchus mykiss / Salmo trutta / Salvelinus fontinalis",
    ambiente: "dulce",
    meses: [11, 12, 1, 2, 3, 4],
    posibles: [5],
    tempAgua: [6, 18],
    horario: "Amanecer y atardecer; eclosiones de insectos. Días nublados en lagos.",
    carnadas: ["(En Patagonia la carnada natural está prohibida en la mayoría de los ambientes)"],
    senuelos: ["Ninfas y moscas secas", "Streamers (wooly bugger, zonker)", "Cucharitas rotativas y ondulantes", "Minnows chicos"],
    metodos: ["Pesca con mosca (fly cast)", "Spinning liviano", "Trolling en lagos (donde esté permitido)"],
    equipo: "Fly: caña #5–#7 con líneas flotante e hundida. Spinning: caña 2,10 m liviana, nylon 0,20–0,25 mm.",
    notas: "Temporada patagónica aprox. 1 de noviembre a abril/mayo. Licencia obligatoria (Parques Nacionales o provincial). Mayoría de ambientes con captura y devolución obligatoria."
  },
  truchaMarron: {
    nombre: "Trucha marrón anádroma (sea-run)",
    cientifico: "Salmo trutta",
    ambiente: "dulce",
    meses: [1, 2, 3, 4],
    posibles: [12],
    tempAgua: [5, 14],
    horario: "Primeras y últimas horas de luz; pozones del río.",
    carnadas: ["(Prohibida la carnada natural)"],
    senuelos: ["Moscas: rubber legs, intruders, streamers oscuros"],
    metodos: ["Pesca con mosca (caña de dos manos / switch)"],
    equipo: "Caña #7–#9 de una o dos manos, líneas de tiro hundidas, tippet 0,30 mm.",
    notas: "Río Grande (Tierra del Fuego) es referencia mundial. Captura y devolución obligatoria."
  },
  perca: {
    nombre: "Perca criolla",
    cientifico: "Percichthys trucha",
    ambiente: "dulce",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [10, 22],
    horario: "Todo el día en costas rocosas y juncales de lagos.",
    carnadas: ["(Consultar: prohibida en Parques Nacionales)"],
    senuelos: ["Cucharitas pequeñas", "Jigs y vinilos chicos", "Moscas (ninfas y streamers)"],
    metodos: ["Spinning ultraliviano", "Pesca con mosca"],
    equipo: "Caña liviana, nylon 0,18–0,22 mm.",
    notas: "Especie nativa patagónica; se recomienda devolución."
  },
  salmonEncerrado: {
    nombre: "Salmón encerrado (landlocked) / Chinook",
    cientifico: "Salmo salar sebago / Oncorhynchus tshawytscha",
    ambiente: "dulce",
    meses: [12, 1, 2, 3],
    posibles: [11, 4],
    tempAgua: [6, 16],
    horario: "Amanecer; desembocaduras de ríos en lagos.",
    carnadas: ["(Prohibida la carnada natural)"],
    senuelos: ["Streamers", "Cucharas ondulantes", "Minnows"],
    metodos: ["Pesca con mosca", "Spinning", "Trolling (donde esté permitido)"],
    equipo: "Fly #6–#8, líneas hundidas; spinning medio.",
    notas: "Lago Traful (salmón encerrado) y río Santa Cruz (chinook). Captura y devolución."
  },

  // ---------------------------- MAR ----------------------------
  corvinaRubia: {
    nombre: "Corvina rubia",
    cientifico: "Micropogonias furnieri",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 9],
    tempAgua: [15, 26],
    horario: "Con marea creciente y agua algo turbia; mejor al atardecer y noche.",
    carnadas: ["Almeja (amarilla o importada)", "Cangrejo", "Langostino", "Filet de lisa o anchoíta", "Calamar"],
    senuelos: ["Jigs y vinilos (embarcado)"],
    metodos: ["Surfcasting con línea de 2 anzuelos y plomo pirámide", "Fondo embarcado", "Pesca de muelle"],
    equipo: "Caña 3,90–4,20 m, reel frontal grande, nylon 0,35–0,40 mm, plomo 80–120 g, anzuelos 1/0–3/0.",
    notas: "Especie más buscada de la costa bonaerense. Talla mínima según provincia."
  },
  corvinaNegra: {
    nombre: "Corvina negra",
    cientifico: "Pogonias courbina",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2],
    posibles: [3, 9],
    tempAgua: [16, 26],
    horario: "Marea creciente; canaletas y bocas de ría.",
    carnadas: ["Cangrejo", "Almeja", "Mejillón", "Langostino"],
    senuelos: [],
    metodos: ["Surfcasting pesado", "Fondo embarcado en canales"],
    equipo: "Caña pesada 4,20 m, nylon 0,45–0,50 mm, plomo 120–150 g, anzuelos 4/0–6/0.",
    notas: "Grandes ejemplares; se recomienda devolver las piezas grandes (reproductores)."
  },
  pescadilla: {
    nombre: "Pescadilla",
    cientifico: "Cynoscion guatucupa",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3, 4],
    posibles: [5, 9],
    tempAgua: [13, 24],
    horario: "Mañana y atardecer; primera rompiente y escolleras.",
    carnadas: ["Filet de anchoíta", "Calamar", "Langostino", "Filet de caballa"],
    senuelos: ["Jigs livianos", "Cucharas"],
    metodos: ["Surfcasting con línea de 2–3 anzuelos", "Muelle y escollera", "Embarcado a la deriva"],
    equipo: "Caña 3,60–4,20 m, nylon 0,30–0,35 mm, plomo 60–100 g, anzuelos 1/0–2/0.",
    notas: "Suele andar en cardúmenes."
  },
  anchoa: {
    nombre: "Anchoa de banco (anchova)",
    cientifico: "Pomatomus saltatrix",
    ambiente: "mar",
    meses: [11, 12, 1, 2, 3, 4],
    posibles: [5, 10],
    tempAgua: [16, 24],
    horario: "Cardúmenes en superficie, amanecer y atardecer.",
    carnadas: ["Filet de anchoíta o caballa", "Anchoíta entera"],
    senuelos: ["Cucharas pesadas", "Poppers", "Jigs metálicos", "Minnows"],
    metodos: ["Spinning desde escollera", "Surfcasting con brazolada de acero"],
    equipo: "Caña 2,70–3,30 m, multifilamento 20–30 lb, líder de acero (dientes filosos).",
    notas: "Aparece por temporadas; seguir los partes de pesca locales."
  },
  brotola: {
    nombre: "Brótola",
    cientifico: "Urophycis brasiliensis",
    ambiente: "mar",
    meses: [5, 6, 7, 8, 9],
    posibles: [4, 10],
    tempAgua: [8, 18],
    horario: "Noche; fondos de piedra y escolleras.",
    carnadas: ["Calamar", "Filet de anchoíta", "Cangrejo", "Langostino"],
    senuelos: [],
    metodos: ["Fondo desde muelle y escollera", "Surfcasting nocturno"],
    equipo: "Caña 3,00–3,90 m, nylon 0,35 mm, anzuelos 1/0–2/0.",
    notas: "Especie invernal típica de Mar del Plata y Necochea."
  },
  lenguado: {
    nombre: "Lenguado",
    cientifico: "Paralichthys spp.",
    ambiente: "mar",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [14, 24],
    horario: "Marea creciente; fondos de arena cerca de canaletas.",
    carnadas: ["Mojarrita o pejerrey chico vivo", "Filet de anchoíta", "Langostino"],
    senuelos: ["Jigs con vinilo arrastrados por el fondo"],
    metodos: ["Fondo con plomada corrida", "Spinning lento en el fondo", "Muelle"],
    equipo: "Caña 2,40–3,60 m, nylon 0,35 mm, anzuelos 2/0.",
    notas: "Clave: movimiento lento del cebo sobre el fondo."
  },
  pejerreyMar: {
    nombre: "Pejerrey de mar (escardón / manila)",
    cientifico: "Odontesthes argentinensis",
    ambiente: "mar",
    meses: [5, 6, 7, 8, 9],
    posibles: [3, 4, 10, 11],
    tempAgua: [8, 18],
    horario: "Mañana; muelles y escolleras con agua clara.",
    carnadas: ["Filet de pejerrey o anchoíta", "Calamarete", "Langostino pelado", "Mejillón"],
    senuelos: ["Moscas chicas"],
    metodos: ["Línea de flote con boyas desde muelle", "Línea de fondo liviana"],
    equipo: "Caña 3,60–4,20 m liviana, nylon 0,22–0,25 mm, anzuelos 1–2.",
    notas: "Presente en toda la costa atlántica."
  },
  tiburones: {
    nombre: "Tiburones (escalandrún, bacota, gatopardo)",
    cientifico: "Carcharias taurus / Carcharhinus brachyurus / Notorynchus cepedianus",
    ambiente: "mar",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [16, 24],
    horario: "Tarde y noche; canaletas profundas y bajíos.",
    carnadas: ["Filet grande de lisa, caballa o pescadilla", "Cabeza de pescado", "Chucho o raya"],
    senuelos: [],
    metodos: ["Surfcasting pesado con brazolada de acero", "Embarcado con fondo"],
    equipo: "Caña 4,20–4,50 m pesada, reel grande, nylon 0,60 mm + leader, brazolada de acero, anzuelos circle 8/0–12/0.",
    notas: "Captura y devolución OBLIGATORIA en Buenos Aires, Río Negro y Chubut para tiburones grandes. Especies amenazadas."
  },
  gatuzo: {
    nombre: "Gatuzo",
    cientifico: "Mustelus schmitti",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 9],
    tempAgua: [12, 22],
    horario: "Tarde y noche; fondos arenosos.",
    carnadas: ["Calamar", "Filet de anchoíta o caballa", "Cangrejo"],
    senuelos: [],
    metodos: ["Surfcasting", "Fondo embarcado"],
    equipo: "Caña 3,90–4,20 m, nylon 0,40 mm, anzuelos 2/0–4/0.",
    notas: "Pequeño tiburón costero; respetar cupos."
  },
  lisa: {
    nombre: "Lisa",
    cientifico: "Mugil liza",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3, 4],
    posibles: [5, 6, 7, 8, 9],
    tempAgua: [14, 28],
    horario: "Marea creciente, canales y bocas de arroyos (aguas salobres).",
    carnadas: ["Masa (harina y queso)", "Lombriz", "Pan", "Mejillón"],
    senuelos: [],
    metodos: ["Línea de flote liviana", "Fondo liviano con cebado"],
    equipo: "Caña 3,00–4,00 m liviana, nylon 0,25 mm, anzuelos chicos 2–6.",
    notas: "Habitual en la Bahía Samborombón y la albufera Mar Chiquita."
  },
  salmonMar: {
    nombre: "Salmón de mar",
    cientifico: "Pseudopercis semifasciata",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4, 9],
    tempAgua: [10, 20],
    horario: "Mañana; restingas y fondos de piedra.",
    carnadas: ["Calamar", "Pulpito", "Cangrejo", "Filet de pescado"],
    senuelos: ["Jigs pesados"],
    metodos: ["Fondo embarcado sobre restingas", "Pesca desde restinga con bajamar"],
    equipo: "Caña 2,10 m pesada, multifilamento 40–60 lb, plomo 150–250 g, anzuelos 4/0–6/0.",
    notas: "Muy apreciado en Golfo San Matías, Península Valdés y San Blas."
  },
  mero: {
    nombre: "Mero",
    cientifico: "Acanthistius patachonicus",
    ambiente: "mar",
    meses: [11, 12, 1, 2, 3],
    posibles: [4, 10],
    tempAgua: [10, 20],
    horario: "Todo el día sobre fondos rocosos.",
    carnadas: ["Calamar", "Cangrejo", "Mejillón", "Filet"],
    senuelos: ["Jigs"],
    metodos: ["Fondo embarcado (pesca variada)"],
    equipo: "Caña 2,10 m media-pesada, multifilamento 30–50 lb, anzuelos 2/0–4/0.",
    notas: "Golfos San Matías y San José."
  },
  robalo: {
    nombre: "Róbalo patagónico",
    cientifico: "Eleginops maclovinus",
    ambiente: "mar",
    meses: [11, 12, 1, 2, 3, 4],
    posibles: [5, 10],
    tempAgua: [6, 16],
    horario: "Con marea creciente en estuarios y rías.",
    carnadas: ["Filet de pescado", "Mejillón", "Lombriz de mar", "Carne"],
    senuelos: ["Cucharitas", "Moscas"],
    metodos: ["Fondo desde costa en estuarios", "Spinning liviano", "Pesca con mosca"],
    equipo: "Caña 2,40–3,00 m media, nylon 0,30 mm, anzuelos 1–1/0.",
    notas: "Típico de rías patagónicas (Deseado, Gallegos, Río Grande, canal Beagle)."
  },
  pezPalo: {
    nombre: "Pez palo",
    cientifico: "Percophis brasiliensis",
    ambiente: "mar",
    meses: [10, 11, 12, 1, 2, 3],
    posibles: [4],
    tempAgua: [12, 22],
    horario: "Mañana; fondos arenosos en canales.",
    carnadas: ["Filet de anchoíta", "Calamar", "Langostino"],
    senuelos: ["Jigs y vinilos"],
    metodos: ["Fondo embarcado", "Spinning de fondo"],
    equipo: "Caña 2,10 m media, multifilamento 20–30 lb.",
    notas: "Habitual en San Blas y costa sur bonaerense."
  }
};

/*
 * Zonas de pesca. Coordenadas aproximadas del centro del área; radioKm
 * define el alcance aproximado de la zona.
 */
const ZONAS = [
  // --- Litoral: Paraná, Paraguay, Uruguay ---
  { id: "paso-patria", nombre: "Paso de la Patria / Itatí", provincia: "Corrientes", lat: -27.31, lng: -58.57, radioKm: 45, ambiente: "dulce", tipo: "Río Paraná (Alto Paraná / confluencia con el Paraguay)", especies: ["dorado", "surubi", "pacu", "boga", "pati", "palometa", "bagre"] },
  { id: "ituzaingo", nombre: "Ituzaingó / Yacyretá", provincia: "Corrientes", lat: -27.58, lng: -56.69, radioKm: 40, ambiente: "dulce", tipo: "Alto Paraná y embalse", especies: ["dorado", "surubi", "pacu", "boga", "bagre"] },
  { id: "ibera", nombre: "Esteros del Iberá", provincia: "Corrientes", lat: -28.54, lng: -57.17, radioKm: 60, ambiente: "dulce", tipo: "Esteros y lagunas", especies: ["tararira", "dorado", "pacu", "bagre"], notas: "Parque Nacional/Provincial: consultar reglamento, predomina captura y devolución." },
  { id: "goya-esquina", nombre: "Goya / Esquina", provincia: "Corrientes", lat: -29.14, lng: -59.26, radioKm: 50, ambiente: "dulce", tipo: "Paraná medio (islas y riachos)", especies: ["dorado", "surubi", "pacu", "boga", "pati", "armado", "palometa", "bagre", "tararira"] },
  { id: "formosa", nombre: "Formosa / Río Paraguay", provincia: "Formosa", lat: -26.18, lng: -58.17, radioKm: 50, ambiente: "dulce", tipo: "Río Paraguay", especies: ["dorado", "surubi", "pacu", "palometa", "bagre"] },
  { id: "la-paz", nombre: "La Paz / Hernandarias", provincia: "Entre Ríos", lat: -30.74, lng: -59.64, radioKm: 45, ambiente: "dulce", tipo: "Paraná medio", especies: ["dorado", "surubi", "boga", "pati", "armado", "bagre", "tararira"] },
  { id: "santa-fe", nombre: "Santa Fe / Paraná", provincia: "Santa Fe / Entre Ríos", lat: -31.65, lng: -60.6, radioKm: 40, ambiente: "dulce", tipo: "Paraná medio y Setúbal", especies: ["dorado", "surubi", "boga", "pati", "armado", "bagre", "tararira", "carpa"] },
  { id: "rosario", nombre: "Rosario / Victoria (islas)", provincia: "Santa Fe / Entre Ríos", lat: -32.9, lng: -60.55, radioKm: 40, ambiente: "dulce", tipo: "Paraná inferior e islas", especies: ["dorado", "boga", "pati", "armado", "bagre", "carpa", "tararira"] },
  { id: "delta", nombre: "Delta del Paraná (Zárate, Campana, Tigre)", provincia: "Buenos Aires", lat: -34.2, lng: -58.85, radioKm: 45, ambiente: "dulce", tipo: "Delta: ríos, arroyos y canales", especies: ["boga", "dorado", "armado", "pati", "bagre", "carpa", "tararira", "pejerrey"] },
  { id: "concordia", nombre: "Concordia / Salto Grande", provincia: "Entre Ríos", lat: -31.27, lng: -57.95, radioKm: 40, ambiente: "dulce", tipo: "Río Uruguay y embalse", especies: ["dorado", "boga", "bagre", "tararira", "carpa", "pati"] },
  { id: "colon", nombre: "Colón / Gualeguaychú", provincia: "Entre Ríos", lat: -32.6, lng: -58.3, radioKm: 55, ambiente: "dulce", tipo: "Río Uruguay inferior", especies: ["boga", "dorado", "bagre", "carpa", "tararira", "pati"] },
  { id: "plata", nombre: "Río de la Plata (Costanera, Punta Lara, Magdalena)", provincia: "Buenos Aires / CABA", lat: -34.85, lng: -57.95, radioKm: 45, ambiente: "dulce", tipo: "Estuario del Plata", especies: ["pejerrey", "boga", "carpa", "bagre", "armado", "corvinaRubia"] },

  // --- NOA / Centro / Cuyo ---
  { id: "cabra-corral", nombre: "Embalse Cabra Corral", provincia: "Salta", lat: -25.28, lng: -65.39, radioKm: 25, ambiente: "dulce", tipo: "Embalse", especies: ["pejerrey", "carpa", "bagre"] },
  { id: "rio-hondo", nombre: "Embalse de Termas de Río Hondo", provincia: "Santiago del Estero", lat: -27.55, lng: -64.87, radioKm: 25, ambiente: "dulce", tipo: "Embalse", especies: ["pejerrey", "carpa", "bagre", "tararira"] },
  { id: "tafi", nombre: "El Mollar / Tafí del Valle (La Angostura)", provincia: "Tucumán", lat: -26.93, lng: -65.7, radioKm: 20, ambiente: "dulce", tipo: "Dique y ríos de montaña", especies: ["trucha", "pejerrey"] },
  { id: "cordoba", nombre: "Embalses de Córdoba (San Roque, Los Molinos, Río Tercero)", provincia: "Córdoba", lat: -31.8, lng: -64.5, radioKm: 60, ambiente: "dulce", tipo: "Embalses serranos", especies: ["pejerrey", "carpa", "bagre", "tararira", "trucha"] },
  { id: "mendoza", nombre: "Embalses de Mendoza (Potrerillos, Valle Grande, Nihuil)", provincia: "Mendoza", lat: -34.9, lng: -68.6, radioKm: 90, ambiente: "dulce", tipo: "Embalses y ríos cordilleranos", especies: ["trucha", "pejerrey", "perca"] },

  // --- Lagunas pampeanas ---
  { id: "chascomus", nombre: "Laguna de Chascomús", provincia: "Buenos Aires", lat: -35.58, lng: -58.02, radioKm: 20, ambiente: "dulce", tipo: "Laguna pampeana", especies: ["pejerrey", "tararira", "carpa", "bagre"] },
  { id: "lobos-monte", nombre: "Lagunas de Lobos y San Miguel del Monte", provincia: "Buenos Aires", lat: -35.35, lng: -58.95, radioKm: 25, ambiente: "dulce", tipo: "Laguna pampeana", especies: ["pejerrey", "tararira", "carpa", "bagre"] },
  { id: "junin", nombre: "Lagunas de Junín (Gómez, Carpincho)", provincia: "Buenos Aires", lat: -34.55, lng: -61.0, radioKm: 25, ambiente: "dulce", tipo: "Laguna pampeana", especies: ["pejerrey", "tararira", "carpa", "bagre"] },
  { id: "encadenadas", nombre: "Lagunas Encadenadas del Oeste", provincia: "Buenos Aires", lat: -37.1, lng: -62.6, radioKm: 50, ambiente: "dulce", tipo: "Sistema de lagunas", especies: ["pejerrey", "carpa"] },
  { id: "las-flores", nombre: "Lagunas del centro bonaerense (Las Flores, Saladillo)", provincia: "Buenos Aires", lat: -35.9, lng: -59.6, radioKm: 50, ambiente: "dulce", tipo: "Lagunas pampeanas", especies: ["pejerrey", "tararira", "carpa", "bagre"] },

  // --- Costa atlántica ---
  { id: "samborombon", nombre: "Bahía Samborombón", provincia: "Buenos Aires", lat: -35.75, lng: -57.3, radioKm: 40, ambiente: "mar", tipo: "Bahía estuarial", especies: ["corvinaNegra", "corvinaRubia", "lisa", "lenguado"] },
  { id: "punta-rasa", nombre: "Punta Rasa / San Clemente del Tuyú", provincia: "Buenos Aires", lat: -36.31, lng: -56.77, radioKm: 30, ambiente: "mar", tipo: "Punta y canaletas", especies: ["corvinaRubia", "corvinaNegra", "pescadilla", "lenguado", "tiburones", "gatuzo", "lisa"] },
  { id: "partido-costa", nombre: "Partido de la Costa / Pinamar / Villa Gesell", provincia: "Buenos Aires", lat: -37.1, lng: -56.85, radioKm: 60, ambiente: "mar", tipo: "Playas y muelles", especies: ["corvinaRubia", "pescadilla", "lenguado", "gatuzo", "brotola", "pejerreyMar"] },
  { id: "mar-chiquita", nombre: "Albufera Mar Chiquita", provincia: "Buenos Aires", lat: -37.73, lng: -57.42, radioKm: 20, ambiente: "mar", tipo: "Albufera (agua salobre)", especies: ["lisa", "corvinaRubia", "lenguado", "pejerreyMar"] },
  { id: "mdp", nombre: "Mar del Plata", provincia: "Buenos Aires", lat: -38.0, lng: -57.53, radioKm: 30, ambiente: "mar", tipo: "Escolleras, muelles y playas", especies: ["pescadilla", "anchoa", "brotola", "lenguado", "pejerreyMar", "gatuzo", "corvinaRubia"] },
  { id: "necochea", nombre: "Necochea / Quequén", provincia: "Buenos Aires", lat: -38.57, lng: -58.7, radioKm: 40, ambiente: "mar", tipo: "Escolleras y playas", especies: ["anchoa", "pescadilla", "brotola", "gatuzo", "tiburones", "pejerreyMar", "corvinaRubia"] },
  { id: "monte-hermoso", nombre: "Monte Hermoso / Pehuen Có", provincia: "Buenos Aires", lat: -38.99, lng: -61.3, radioKm: 50, ambiente: "mar", tipo: "Playas", especies: ["pescadilla", "gatuzo", "corvinaRubia", "lenguado", "tiburones", "pezPalo"] },
  { id: "san-blas", nombre: "Bahía San Blas", provincia: "Buenos Aires", lat: -40.55, lng: -62.25, radioKm: 35, ambiente: "mar", tipo: "Bahía y canales", especies: ["tiburones", "corvinaRubia", "salmonMar", "pezPalo", "gatuzo", "pescadilla", "mero"] },
  { id: "las-grutas", nombre: "Las Grutas / Golfo San Matías", provincia: "Río Negro", lat: -40.81, lng: -65.08, radioKm: 45, ambiente: "mar", tipo: "Golfo y restingas", especies: ["salmonMar", "mero", "pejerreyMar", "robalo", "tiburones"] },
  { id: "madryn", nombre: "Puerto Madryn / Península Valdés", provincia: "Chubut", lat: -42.77, lng: -64.9, radioKm: 70, ambiente: "mar", tipo: "Golfos Nuevo y San José", especies: ["salmonMar", "mero", "pejerreyMar", "robalo"] },
  { id: "camarones", nombre: "Camarones / Comodoro Rivadavia", provincia: "Chubut", lat: -45.3, lng: -67.2, radioKm: 90, ambiente: "mar", tipo: "Costa patagónica", especies: ["robalo", "pejerreyMar", "salmonMar", "mero"] },
  { id: "deseado", nombre: "Ría Deseado", provincia: "Santa Cruz", lat: -47.75, lng: -65.95, radioKm: 35, ambiente: "mar", tipo: "Ría", especies: ["robalo", "pejerreyMar"] },
  { id: "gallegos", nombre: "Río Gallegos (estuario)", provincia: "Santa Cruz", lat: -51.63, lng: -69.22, radioKm: 35, ambiente: "mar", tipo: "Estuario", especies: ["robalo", "pejerreyMar", "truchaMarron"] },
  { id: "beagle", nombre: "Ushuaia / Canal Beagle", provincia: "Tierra del Fuego", lat: -54.82, lng: -68.3, radioKm: 40, ambiente: "mar", tipo: "Canal y ríos fueguinos", especies: ["robalo", "pejerreyMar", "trucha"] },

  // --- Patagonia agua dulce ---
  { id: "chocon", nombre: "El Chocón / Ramos Mexía", provincia: "Neuquén", lat: -39.3, lng: -68.9, radioKm: 50, ambiente: "dulce", tipo: "Embalse y río Limay inferior", especies: ["trucha", "perca", "pejerrey"] },
  { id: "junin-andes", nombre: "Junín de los Andes (Chimehuín, Malleo, Aluminé)", provincia: "Neuquén", lat: -39.95, lng: -71.08, radioKm: 45, ambiente: "dulce", tipo: "Ríos y lagos cordilleranos", especies: ["trucha", "perca"] },
  { id: "san-martin", nombre: "San Martín de los Andes (Lácar, Meliquina)", provincia: "Neuquén", lat: -40.15, lng: -71.35, radioKm: 30, ambiente: "dulce", tipo: "Lagos cordilleranos", especies: ["trucha", "perca"] },
  { id: "traful", nombre: "Villa Traful / Lago Traful", provincia: "Neuquén", lat: -40.65, lng: -71.4, radioKm: 25, ambiente: "dulce", tipo: "Lago cordillerano", especies: ["salmonEncerrado", "trucha", "perca"] },
  { id: "bariloche", nombre: "Bariloche / Nahuel Huapi / Limay superior", provincia: "Río Negro", lat: -41.13, lng: -71.3, radioKm: 40, ambiente: "dulce", tipo: "Lagos y río Limay", especies: ["trucha", "perca", "salmonEncerrado"] },
  { id: "esquel", nombre: "Esquel / Los Alerces / Futaleufú", provincia: "Chubut", lat: -42.9, lng: -71.6, radioKm: 55, ambiente: "dulce", tipo: "Lagos y ríos cordilleranos", especies: ["trucha", "perca"] },
  { id: "strobel", nombre: "Lago Strobel (Jurassic Lake)", provincia: "Santa Cruz", lat: -48.5, lng: -71.2, radioKm: 40, ambiente: "dulce", tipo: "Lago de meseta", especies: ["trucha"], notas: "Truchas arco iris de gran porte; acceso por estancias/lodges." },
  { id: "santa-cruz", nombre: "Río Santa Cruz", provincia: "Santa Cruz", lat: -50.1, lng: -70.3, radioKm: 80, ambiente: "dulce", tipo: "Río patagónico", especies: ["trucha", "salmonEncerrado"] },
  { id: "rio-grande", nombre: "Río Grande", provincia: "Tierra del Fuego", lat: -53.79, lng: -67.9, radioKm: 50, ambiente: "dulce", tipo: "Río fueguino", especies: ["truchaMarron", "trucha", "robalo"] }
];

const MESES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"];
